<?php
/**
 * AppProjectWriterServiceModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wirk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Wirk\Model;

use \ArrayAccess;
/**
 * AppProjectWriterServiceModel Class Doc Comment
 *
 * @category    Class
 * @description Model for AppProject
 * @package     Wirk
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppProjectWriterServiceModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id_app' => 'int',
        'id_quality' => 'int',
        'instruction' => 'string',
        'question_options' => 'string[]',
        'title' => 'string',
        'url_notification' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id_app' => 'IdApp',
        'id_quality' => 'IdQuality',
        'instruction' => 'Instruction',
        'question_options' => 'QuestionOptions',
        'title' => 'Title',
        'url_notification' => 'UrlNotification'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id_app' => 'setIdApp',
        'id_quality' => 'setIdQuality',
        'instruction' => 'setInstruction',
        'question_options' => 'setQuestionOptions',
        'title' => 'setTitle',
        'url_notification' => 'setUrlNotification'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id_app' => 'getIdApp',
        'id_quality' => 'getIdQuality',
        'instruction' => 'getInstruction',
        'question_options' => 'getQuestionOptions',
        'title' => 'getTitle',
        'url_notification' => 'getUrlNotification'
    );
  
    
    /**
      * $id_app 
      * @var int
      */
    protected $id_app;
    
    /**
      * $id_quality 
      * @var int
      */
    protected $id_quality;
    
    /**
      * $instruction 
      * @var string
      */
    protected $instruction;
    
    /**
      * $question_options 
      * @var string[]
      */
    protected $question_options;
    
    /**
      * $title 
      * @var string
      */
    protected $title;
    
    /**
      * $url_notification 
      * @var string
      */
    protected $url_notification;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->id_app = $data["id_app"];
            $this->id_quality = $data["id_quality"];
            $this->instruction = $data["instruction"];
            $this->question_options = $data["question_options"];
            $this->title = $data["title"];
            $this->url_notification = $data["url_notification"];
        }
    }
    
    /**
     * Gets id_app
     * @return int
     */
    public function getIdApp()
    {
        return $this->id_app;
    }
  
    /**
     * Sets id_app
     * @param int $id_app 
     * @return $this
     */
    public function setIdApp($id_app)
    {
        
        $this->id_app = $id_app;
        return $this;
    }
    
    /**
     * Gets id_quality
     * @return int
     */
    public function getIdQuality()
    {
        return $this->id_quality;
    }
  
    /**
     * Sets id_quality
     * @param int $id_quality 
     * @return $this
     */
    public function setIdQuality($id_quality)
    {
        
        $this->id_quality = $id_quality;
        return $this;
    }
    
    /**
     * Gets instruction
     * @return string
     */
    public function getInstruction()
    {
        return $this->instruction;
    }
  
    /**
     * Sets instruction
     * @param string $instruction 
     * @return $this
     */
    public function setInstruction($instruction)
    {
        
        $this->instruction = $instruction;
        return $this;
    }
    
    /**
     * Gets question_options
     * @return string[]
     */
    public function getQuestionOptions()
    {
        return $this->question_options;
    }
  
    /**
     * Sets question_options
     * @param string[] $question_options 
     * @return $this
     */
    public function setQuestionOptions($question_options)
    {
        
        $this->question_options = $question_options;
        return $this;
    }
    
    /**
     * Gets title
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
  
    /**
     * Sets title
     * @param string $title 
     * @return $this
     */
    public function setTitle($title)
    {
        
        $this->title = $title;
        return $this;
    }
    
    /**
     * Gets url_notification
     * @return string
     */
    public function getUrlNotification()
    {
        return $this->url_notification;
    }
  
    /**
     * Sets url_notification
     * @param string $url_notification 
     * @return $this
     */
    public function setUrlNotification($url_notification)
    {
        
        $this->url_notification = $url_notification;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Wirk\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Wirk\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
