<?php
/**
 * TaskLineReaderServiceModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wirk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Wirk\Model;

use \ArrayAccess;
/**
 * TaskLineReaderServiceModel Class Doc Comment
 *
 * @category    Class
 * @description Model for TaskLineReaderServiceModel
 * @package     Wirk
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskLineReaderServiceModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id_app_project' => 'int',
        'id_task_line' => 'int',
        'inputs' => 'string[]',
        'tasks' => '\Wirk\Model\TaskReaderServiceModel[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id_app_project' => 'IdAppProject',
        'id_task_line' => 'IdTaskLine',
        'inputs' => 'Inputs',
        'tasks' => 'Tasks'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id_app_project' => 'setIdAppProject',
        'id_task_line' => 'setIdTaskLine',
        'inputs' => 'setInputs',
        'tasks' => 'setTasks'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id_app_project' => 'getIdAppProject',
        'id_task_line' => 'getIdTaskLine',
        'inputs' => 'getInputs',
        'tasks' => 'getTasks'
    );
  
    
    /**
      * $id_app_project 
      * @var int
      */
    protected $id_app_project;
    
    /**
      * $id_task_line 
      * @var int
      */
    protected $id_task_line;
    
    /**
      * $inputs 
      * @var string[]
      */
    protected $inputs;
    
    /**
      * $tasks 
      * @var \Wirk\Model\TaskReaderServiceModel[]
      */
    protected $tasks;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->id_app_project = $data["id_app_project"];
            $this->id_task_line = $data["id_task_line"];
            $this->inputs = $data["inputs"];
            $this->tasks = $data["tasks"];
        }
    }
    
    /**
     * Gets id_app_project
     * @return int
     */
    public function getIdAppProject()
    {
        return $this->id_app_project;
    }
  
    /**
     * Sets id_app_project
     * @param int $id_app_project 
     * @return $this
     */
    public function setIdAppProject($id_app_project)
    {
        
        $this->id_app_project = $id_app_project;
        return $this;
    }
    
    /**
     * Gets id_task_line
     * @return int
     */
    public function getIdTaskLine()
    {
        return $this->id_task_line;
    }
  
    /**
     * Sets id_task_line
     * @param int $id_task_line 
     * @return $this
     */
    public function setIdTaskLine($id_task_line)
    {
        
        $this->id_task_line = $id_task_line;
        return $this;
    }
    
    /**
     * Gets inputs
     * @return string[]
     */
    public function getInputs()
    {
        return $this->inputs;
    }
  
    /**
     * Sets inputs
     * @param string[] $inputs 
     * @return $this
     */
    public function setInputs($inputs)
    {
        
        $this->inputs = $inputs;
        return $this;
    }
    
    /**
     * Gets tasks
     * @return \Wirk\Model\TaskReaderServiceModel[]
     */
    public function getTasks()
    {
        return $this->tasks;
    }
  
    /**
     * Sets tasks
     * @param \Wirk\Model\TaskReaderServiceModel[] $tasks 
     * @return $this
     */
    public function setTasks($tasks)
    {
        
        $this->tasks = $tasks;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Wirk\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Wirk\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
